game: main.cpp Player.cpp Enemy.cpp Cell.cpp Field.cpp Game.cpp EnemyBuilding.cpp CombatManager.cpp
	g++ main.cpp Player.cpp Enemy.cpp Cell.cpp Field.cpp Game.cpp EnemyBuilding.cpp CombatManager.cpp Spell.cpp SpellHand.cpp DirectDamageSpell.cpp AreaDamageSpell.cpp SpellCasting.cpp -o game

clean:
	rm -f game